### ISSUE TITLE
Missing rules and/or file openarc/openarc.conf.sample

### ISSUE THREAD

**Issue by smjones** [mskucherawy/OpenARC#2] opened 2016-05-26 20:06 UTC
First build of the package died because there was no openarc/openarc.conf.sample file, and no rules to create it. Perhaps it should be referring to openarc.conf.simple, which is present?

Complete build log attached just in case the preceding messages are wanted for review.

FreeBSD $HOSTNAME 10.2-RELEASE-p14 FreeBSD 10.2-RELEASE-p14 #0: Wed Mar 16 20:46:12 UTC 2016     root@amd64-builder.daemonology.net:/usr/obj/usr/src/sys/GENERIC  amd64

[openarc-build-1.log.txt](https://github.com/mskucherawy/OpenARC/files/285240/openarc-build-1.log.txt)

**Comment by mskucherawy** [comment] 2016-06-26 06:12
The package correctly includes this file now, but it is empty.  When the configuration list has settled, someone needs to generate this.

For the sake of showing intended format and content, the OpenDKIM equivalent is:
https://sourceforge.net/p/opendkim/git/ci/master/tree/opendkim/opendkim.conf.sample

**Comment by z3APA3A** [comment] 2017-06-12 14:31
The problem is you included 
openarc.conf.s_**i**_mple
while the file listed in makefile is
openarc.conf.sample

**Comment by flowerysong** [comment] 2017-07-13 18:05
Fixed in 2fb819936cfbd9d7add362731b30f91542e47b4d; this issue can be closed.

**Closed** 2017-07-16 03:04 UTC
