### ISSUE TITLE
Where is the INSTALL file? How do I compile this?

### ISSUE THREAD

**Issue by raforg** [mskucherawy/OpenARC#148] opened 2021-08-17 11:30 UTC
The README file refers to files named INSTALL and FEATURES that do not exist in the repository. I can't find any instructions on how to compile openarc, let alone install it. There are plenty of Makefile.am files, but no instructions on what to do with them. It might be obvious to you, but not to everyone. There are no configure scripts and no actual Makefiles. Don't make us work out how to do it. Just tell us. Did you forget to git add them?

**Comment by glts** [comment] 2021-08-17 12:42
Strictly speaking this is a duplicate of #118. I believe to those who have been following these projects for some time, the impression that they have been abandoned is unfortunately quite strong. And of all of them, OpenARC is in the least good shape.

For Debian I have recently attempted to produce an experimental openarc package at https://salsa.debian.org/glts/openarc. It is working, so perhaps that could be a useful starting point.

**Comment by flowerysong** [comment] 2021-08-17 17:11
The "missing" configure scripts (and other build tooling) are artifacts which should be included in release archives but not checked in to your SCM, so having to generate them when building from a git checkout is a normal step. The "maintainers" of this project haven't been building release archives so they're not included in releases either, but that would be easy to fix if the project wasn't dead.

```
autoreconf -fi
./configure
make
```

You should also apply https://github.com/trusteddomainproject/OpenARC/pull/121, since it's very important if you want correct handling of existing ARC chains.

**Comment by raforg** [comment] 2021-08-22 10:23
Thanks.

**Closed as completed** 2021-08-22 10:28 UTC
